// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ-fp6aPoPknSsm9MZlQT4ws-oRQzf83A',
    appId: '1:283622304387:web:2a62382b396538784789b6',
    messagingSenderId: '283622304387',
    projectId: 'gofoodzex',
    authDomain: 'gofoodzex.firebaseapp.com',
    storageBucket: 'gofoodzex.appspot.com',
    measurementId: 'G-N3G1FH6V5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSz0vO9qJWnZg9VnbEColGuwDbV6SR16I',
    appId: '1:283622304387:android:d2799c4d4079664e4789b6',
    messagingSenderId: '283622304387',
    projectId: 'gofoodzex',
    storageBucket: 'gofoodzex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVhXjXPouYdG6CFq47eJ14RG72vMijzNs',
    appId: '1:283622304387:ios:d10714ebae4588ef4789b6',
    messagingSenderId: '283622304387',
    projectId: 'gofoodzex',
    storageBucket: 'gofoodzex.appspot.com',
    iosClientId: '283622304387-0comejqff9188umfrbls4voqvb7m50cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.goFoodz',
  );
}
